### ISSUE TITLE
How escape special char in values (e.g. separator)

### ISSUE THREAD

**Issue by KarolPiechoczek** [salaros/config-parser#16]
Hello,
how I can escape "=" char in my value?

Example:
```
[Advanced]
Select =
	 select * from
	 from table
	 where ID = '5'
```

Array return only two first lines. Third line is ignored. **I don't want change separator.**

OR...

How to convert this multi-line value to one line (by ignoring carriage return)?

```
[Advanced]
ExampleValue = Lorem ipsum dolor sit amet
consectetur adipiscing elit
sed do eiusmod tempor incididunt
```

**Comment by salaros** [comment]
As for the first one: it's not a trivial problem, since your multi-line (array) value contains a completely valid key, but I manged to work it around.

As for the second one, once you read a multiline value you can use `string.Joing(" ", multilineValue);` to make it one line, separated by white-spaces, however some users might just WANT it to be multi-line text.
I added a helper method for your `JoinMultilineValue(section, key)` 

Please download 0.3.7 and take a look

**Comment by salaros** [comment]
@KarolPiechoczek Please consider starring and sharing this repo! It helps us getting known and grow the community.

![](https://github.com/salaros/config-parser/raw/master/.github/assets/star_us.gif)
